import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CRUD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-[768px] w-full mx-auto">
          <header className="bg-[pink] border-b rounded-[12px] p-[24px] flex justify-between items-center">
            <Link href={"/"} className="no-underline text-[black] text-[24px] font-bold">
              Tech Interpretations
            </Link>
            <Link
              href={"/create"}
              className="no-underline text-[black] bg-[#06dc06] p-[8px] rounded-[7px]"
            >
              + Add New
            </Link>
          </header>
          <main className="p-[16px] text-[20px]">{children}</main>
        </div>
      </body>
    </html>
  );
}
